on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

name: release
jobs:
  build:
    uses: ritzk/com.larksuite.Lark/.github/workflows/build.yml@main

  release:
    needs: build
    runs-on: self-hosted
    steps:
    - name: download artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: lark-*.flatpak
    - uses: ncipollo/release-action@v1
      with:
        artifacts: lark-*.flatpak
